export const SET_CONTACT_LIST="SET_CONTACT_LIST"
export const SET_CONTACT_LIST_SUCCESS="SET_CONTACT_LIST_SUCCESS"
export const SET_CONTACT_LIST_FAILURE="SET_CONTACT_LIST_FAILURE"

export const SET_ROOM="SET_ROOM"
export const SET_ROOM_SUCCESS="SET_ROOM_SUCCESS"
export const SET_ROOM_FAILURE="SET_ROOM_FAILURE"


export const SET_INVITES="SET_INVITES"
export const SET_INVITES_SUCCESS="SET_INVITES_SUCCESS"
export const SET_INVITES_FAILURE="SET_INVITES_FAILURE"

export const SET_SUGGESTED="SET_SUGGESTED"
export const SET_SUGGESTED_SUCCESS="SET_SUGGESTED_SUCCESS"
export const SET_SUGGESTED_FAILURE="SET_SUGGESTED_FAILURE"


export const SET_CIRCLE="SET_CIRCLE"
export const SET_CIRCLE_SUCCESS="SET_CIRCLE_SUCCESS"
export const SET_CIRCLE_FAILURE="SET_CIRCLE_FAILURE"

export const SET_MESSAGES="SET_MESSAGES"
export const SET_MESSAGES_SUCCESS="SET_MESSAGES_SUCCESS"
export const SET_MESSAGES_FAILURE="SET_MESSAGES_FAILURE"

