export const OPEN_LEFT_LANDING="OPEN_LEFT_LANDING"
export const OPEN_RIGHT_PROFILE="OPEN_RIGHT_PROFILE"



export const CLOSE_LEFT_LANDING="CLOSE_LEFT_LANDING"
export const CLOSE_RIGHT_PROFILE="CLOSE_RIGHT_PROFILE"

export const SHOW_TOAST_MESSAGE="SHOW_TOAST_MESSAGE"
export const SHOW_TOAST_MESSAGE_SUCCESS="SHOW_TOAST_MESSAGE_SUCCESS"
export const SHOW_TOAST_MESSAGE_FAILURE="SHOW_TOAST_MESSAGE_FAILURE"

export const SET_FOOTER_OPEN="SET_FOOTER_OPEN"
export const SET_FOOTER_CLOSE="SET_FOOTER_CLOSE"

export const OPEN_INDIVIDUAL_BOOKING_PANEL="OPEN_INDIVIDUAL_BOOKING_PANEL"
export const CLOSE_INDIVIDUAL_BOOKING_PANEL="CLOSE_INDIVIDUAL_BOOKING_PANEL"

export const OPEN_PROJECT_BOOKING_PANEL="OPEN_PROJECT_BOOKING_PANEL"
export const CLOSE_PROJECT_BOOKING_PANEL="CLOSE_PROJECT_BOOKING_PANEL"

export const OPEN_OPENING_PANEL="OPEN_OPENING_PANEL"
export const CLOSE_OPENING_PANEL="CLOSE_OPENING_PANEL"

export const OPEN_EDIT_ADDRESS_PANEL="OPEN_EDIT_ADDRESS_PANEL"
export const CLOSE_EDIT_ADDRESS_PANEL="CLOSE_EDIT_ADDRESS_PANEL"

export const OPEN_IMAGE_PANEL="OPEN_IMAGE_PANEL"
export const CLOSE_IMAGE_PANEL="CLOSE_IMAGE_PANEL"

export const OPEN_DETAIL_PANEL="OPEN_DETAIL_PANEL"
export const CLOSE_DETAIL_PANEL="CLOSE_DETAIL_PANEL"


export const OPEN_ACTION_PANEL="OPEN_ACTION_PANEL"
export const CLOSE_ACTION_PANEL="CLOSE_ACTION_PANEL"

export const OPEN_PAY_PANEL="OPEN_PAY_PANEL"
export const CLOSE_PAY_PANEL="CLOSE_PAY_PANEL"

export const OPEN_PROJECT_PANEL="OPEN_PROJECT_PANEL"
export const CLOSE_PROJECT_PANEL="CLOSE_PROJECT_PANEL"

export const OPEN_APPLICATION_PANEL="OPEN_APPLICATION_PANEL"
export const CLOSE_APPLICATION_PANEL="CLOSE_APPLICATION_PANEL"


export const HIDE_HEADER="HIDE_HEADER"
export const HIDE_FOOTER="HIDE_FOOTER"

export const OPEN_POST_STAT_PANEL="OPEN_POST_STAT_PANEL"
export const CLOSE_POST_STAT_PANEL="CLOSE_POST_STAT_PANEL"

export const OPEN_POST_COMMENT_PANEL="OPEN_POST_COMMENT_PANEL"
export const CLOSE_POST_COMMENT_PANEL="CLOSE_POST_COMMENT_PANEL"


export const OPEN_HOURLY_BOOKING_PANEL="OPEN_HOURLY_BOOKING_PANEL"
export const CLOSE_HOURLY_BOOKING_PANEL="CLOSE_HOURLY_BOOKING_PANEL"

export const OPEN_FORM_PANEL="OPEN_FORM_PANEL"
export const CLOSE_FORM_PANEL="CLOSE_FORM_PANEL"

export const OPEN_LOCALIZER_PANEL="OPEN_LOCALIZER_PANEL"
export const CLOSE_LOCALIZER_PANEL="CLOSE_LOCALIZER_PANEL"

export const OPEN_POST_CREATE_PANEL="OPEN_POST_CREATE_PANEL"
export const CLOSE_POST_CREATE_PANEL="CLOSE_POST_CREATE_PANEL"

export const OPEN_POST_MENU_PANEL="OPEN_POST_MENU_PANEL"
export const CLOSE_POST_MENU_PANEL="CLOSE_POST_MENU_PANEL"



export const OPEN_COUPON_PANEL="OPEN_COUPON_PANEL"
export const OPEN_COUPON_PANEL_SUCCESS="OPEN_COUPON_PANEL_SUCCESS"
export const OPEN_COUPON_PANEL_FAILURE="OPEN_COUPON_PANEL_FAILURE"

export const CLOSE_COUPON_PANEL="CLOSE_COUPON_PANEL"

