
export const ADD_TO_CART= "ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const ADD_QUANTITY="ADD_QUANTITY"
export const REMOVE_QUANTITY="REMOVE_QUANTITY"


export const SET_DELIVERY_ADDRESS="SET_DELIVERY_ADDRESS"
export const SET_DELIVERY_ADDRESS_SUCCESS="SET_DELIVERY_ADDRESS_SUCCESS"
export const SET_DELIVERY_ADDRESS_FAILURE="SET_DELIVERY_ADDRESS_FAILURE"


export const SET_USER_ADDRESSES="SET_USER_ADDRESSES"
export const SET_USER_ADDRESSES_SUCCESS="SET_USER_ADDRESSES_SUCCESS"
export const SET_USER_ADDRESSES_FAILURE="SET_USER_ADDRESSES_FAILURE"




export const RESET_AFTER_INVOICE = "RESET_AFTER_INVOICE"

export const RESET_AFTER_SIGNOUT = "RESET_AFTER_SIGNOUT"
