export const UPDATE_SHORT="UPDATE_SHORT"
export const UPDATE_SHORT_SUCCESS="UPDATE_SHORT_SUCCESS"
export const UPDATE_SHORT_FAILURE="UPDATE_SHORT_FAILURE"


export const REMOVE_SHORT="REMOVE_SHORT"
export const REMOVE_SHORT_SUCCESS="REMOVE_SHORT_SUCCESS"
export const REMOVE_SHORT_FAILURE="REMOVE_SHORT_FAILURE"




export const CREATE_SHORT="CREATE_SHORT"
export const CREATE_SHORT_SUCCESS="CREATE_SHORT_SUCCESS"
export const CREATE_SHORT_FAILURE="CREATE_SHORT_FAILURE"

