export const CREATE_NOTIFICATION="CREATE_NOTIFICATION"
export const CREATE_NOTIFICATION_SUCCESS="CREATE_NOTIFICATION_SUCCESS"
export const CREATE_NOTIFICATION_FAILURE="CREATE_NOTIFICATION_FAILURE"

export const GET_NOTIFICATIONS="GET_NOTIFICATIONS"
export const GET_NOTIFICATIONS_SUCCESS="GET_NOTIFICATIONS_SUCCESS"
export const GET_NOTIFICATIONS_FAILURE="GET_NOTIFICATIONS_FAILURE"



