export const UPDATE_PROJECT="UPDATE_PROJECT"
export const UPDATE_PROJECT_SUCCESS="UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_FAILURE="UPDATE_PROJECT_FAILURE"

export const SET_USER_PROJECTS="SET_USER_PROJECTS"
export const SET_USER_PROJECTS_SUCCESS="SET_USER_PROJECTS_SUCCESS"
export const SET_USER_PROJECTS_FAILURE="SET_USER_PROJECTS_FAILURE"


export const REMOVE_PROJECT="REMOVE_PROJECT"
export const REMOVE_PROJECT_SUCCESS="REMOVE_PROJECT_SUCCESS"
export const REMOVE_PROJECT_FAILURE="REMOVE_PROJECT_FAILURE"


export const CREATE_PROJECT="CREATE_PROJECT"
export const CREATE_PROJECT_SUCCESS="CREATE_PROJECT_SUCCESS"
export const CREATE_PROJECT_FAILURE="CREATE_PROJECT_FAILURE"

export const UPDATE_PROJECT_SCRIPT="UPDATE_PROJECT_SCRIPT"
export const UPDATE_PROJECT_SCRIPT_SUCCESS="UPDATE_PROJECT_SCRIPT_SUCCESS"
export const UPDATE_PROJECT_SCRIPT_FAILURE="UPDATE_PROJECT_SCRIPT_FAILURE"


export const REMOVE_PROJECT_SCRIPT="REMOVE_PROJECT_SCRIPT"
export const REMOVE_PROJECT_SCRIPT_SUCCESS="REMOVE_PROJECT_SCRIPT_SUCCESS"
export const REMOVE_PROJECT_SCRIPT_FAILURE="REMOVE_PROJECT_SCRIPT_FAILURE"


export const CREATE_PROJECT_SCRIPT="CREATE_PROJECT_SCRIPT"
export const CREATE_PROJECT_SCRIPT_SUCCESS="CREATE_PROJECT_SCRIPT_SUCCESS"
export const CREATE_PROJECT_SCRIPT_FAILURE="CREATE_PROJECT_SCRIPT_FAILURE"


export const UPDATE_PROJECT_INFO="UPDATE_PROJECT_INFO"
export const UPDATE_PROJECT_INFO_SUCCESS="UPDATE_PROJECT_INFO_SUCCESS"
export const UPDATE_PROJECT_INFO_FAILURE="UPDATE_PROJECT_INFO_FAILURE"


export const REMOVE_PROJECT_INFO="REMOVE_PROJECT_INFO"
export const REMOVE_PROJECT_INFO_SUCCESS="REMOVE_PROJECT_INFO_SUCCESS"
export const REMOVE_PROJECT_INFO_FAILURE="REMOVE_PROJECT_INFO_FAILURE"


export const CREATE_PROJECT_INFO="CREATE_PROJECT_INFO"
export const CREATE_PROJECT_INFO_SUCCESS="CREATE_PROJECT_INFO_SUCCESS"
export const CREATE_PROJECT_INFO_FAILURE="CREATE_PROJECT_INFO_FAILURE"

export const UPDATE_PROJECT_POSTER="UPDATE_PROJECT_POSTER"
export const UPDATE_PROJECT_POSTER_SUCCESS="UPDATE_PROJECT_POSTER_SUCCESS"
export const UPDATE_PROJECT_POSTER_FAILURE="UPDATE_PROJECT_POSTER_FAILURE"


export const REMOVE_PROJECT_POSTER="REMOVE_PROJECT_POSTER"
export const REMOVE_PROJECT_POSTER_SUCCESS="REMOVE_PROJECT_POSTER_SUCCESS"
export const REMOVE_PROJECT_POSTER_FAILURE="REMOVE_PROJECT_POSTER_FAILURE"

export const CREATE_PROJECT_POSTER="CREATE_PROJECT_POSTER"
export const CREATE_PROJECT_POSTER_SUCCESS="CREATE_PROJECT_POSTER_SUCCESS"
export const CREATE_PROJECT_POSTER_FAILURE="CREATE_PROJECT_POSTER_FAILURE"


export const RESET_PROJECTS="RESET_PROJECTS"