export const CREATE_OFFER="CREATE_OFFER"
export const CREATE_OFFER_SUCCESS="CREATE_OFFER_SUCCESS"
export const CREATE_OFFER_FAILURE="CREATE_OFFER_FAILURE"

export const REJECT_OFFER="REJECT_OFFER"
export const REJECT_OFFER_SUCCESS="REJECT_OFFER_SUCCESS"
export const REJECT_OFFER_FAILURE="REJECT_OFFER_FAILURE"


export const CREATE_ANSWER="CREATE_ANSWER"
export const CREATE_ANSWER_SUCCESS="CREATE_ANSWER_SUCCESS"
export const CREATE_ANSWER_FAILURE="CREATE_ANSWER_FAILURE"

export const START_CALL="START_CALL"
export const START_CALL_SUCCESS="START_CALL_SUCCESS"
export const START_CALL_FAILURE="START_CALL_FAILURE"


export const END_CALL="END_CALL"
export const END_CALL_SUCCESS="END_CALL_SUCCESS"
export const END_CALL_FAILURE="END_CALL_FAILURE"
