export const UPDATE_SHOP="UPDATE_SHOP"
export const UPDATE_SHOP_SUCCESS="UPDATE_SHOP_SUCCESS"
export const UPDATE_SHOP_FAILURE="UPDATE_SHOP_FAILURE"


export const CREATE_SHOP="CREATE_SHOP"
export const CREATE_SHOP_SUCCESS="CREATE_SHOP_SUCCESS"
export const CREATE_SHOP_FAILURE="CREATE_SHOP_FAILURE"
