export const SET_LOCAL_REGION="SET_LOCAL_REGION" 
export const SET_LOCAL_REGION_SUCCESS="SET_LOCAL_REGION_SUCCESS" 
export const SET_LOCAL_REGION_FAILURE="SET_LOCAL_REGION_FAILURE" 

export const SET_CURRENCY="SET_CURRENCY"
export const SET_CURRENCY_SUCCESS="SET_CURRENCY_SUCCESS" 
export const SET_CURRENCY_FAILURE="SET_CURRENCY_FAILURE" 

export const SET_CURRENCY_RATES="SET_CURRENCY_RATES"
export const SET_CURRENCY_RATES_SUCCESS="SET_CURRENCY_RATES_SUCCESS"
export const SET_CURRENCY_RATES_FAILURE="SET_CURRENCY_RATES_FAILURE"


export const SET_LOCAL_CONTACTS="SET_LOCAL_CONTACTS"
export const SET_LOCAL_CONTACTS_SUCCESS="SET_LOCAL_CONTACTS_SUCCESS"
export const SET_LOCAL_CONTACTS_FAILURE="SET_LOCAL_CONTACTS_FAILURE"
