export const REGISTER="REGISTER"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"

export const LOGIN="LOGIN"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"


export const RESET_PASSWORD="RESET_PASSWORD"
export const  RESET_PASSWORD_SUCCESS=" RESET_PASSWORD_SUCCESS"
export const  RESET_PASSWORD_FAILURE=" RESET_PASSWORD_FAILURE"

export const SIGNOUT="SIGNOUT"
export const SIGNOUT_SUCCESS="SIGNOUT_SUCCESS"
export const SIGNOUT_FAILURE="SIGNOUT_FAILURE"

export const AUTHENTICATE="AUTHENTICATE" 

export const UPDATE_USER_PROFILED_STATUS="UPDATE_USER_PROFILED_STATUS"
export const UPDATE_USER_PROFILED_STATUS_SUCCESS="UPDATE_USER_PROFILED_STATUS_SUCCESS"

export const UPDATE_USER_PROFILED_STATUS_FAILURE="UPDATE_USER_PROFILED_STATUS_FAILURE"

