export const UPDATE_PROFILE="UPDATE_PROFILE"
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILURE="UPDATE_PROFILE_FAILURE"


export const CREATE_PROFILE="CREATE_PROFILE"
export const CREATE_PROFILE_SUCCESS="CREATE_PROFILE_SUCCESS"
export const CREATE_PROFILE_FAILURE="CREATE_PROFILE_FAILURE"


export const RESET_PROFILE="RESET_PROFILE"