export const SET_OPENINGS="SET_OPENINGS"
export const SET_OPENINGS_SUCCESS="SET_OPENINGS_SUCCESS"
export const SET_OPENINGS_FAILURE="SET_OPENINGS_FAILURE"

export const APPLY_ON_OPENING="APPLY_ON_OPENING"
export const IGNORE_OPENING="IGNORE_OPENING"

export const REPORT_OPENING="REOPRT_OPENING"
export const DELETE_OPENING="DELETE_OPENING"

export const SHORTLIST_CANDIDTATE="SHORTLIST_CANDIDTATE"
export const REJECT_CANDIDTATE="REJECT_CANDIDTATE"
export const SELECT_CANDIDTATE="SELECT_CANDIDTATE"

export const CLOSE_OPENING="CLOSE_OPENING"

export const GET_USER_APPLICATIONS="GET_USER_APPLICATIONS"
export const GET_USER_APPLICATIONS_SUCCESS="GET_USER_APPLICATIONS_SUCCESS"
export const GET_USER_APPLICATIONS_FAILURE="GET_USER_APPLICATIONS_FAILURE"

export const UPDATE_USER_APPLICATIONS="UPDATE_USER_APPLICATIONS"
export const UPDATE_USER_APPLICATIONS_SUCCESS="UPDATE_USER_APPLICATIONS_SUCCESS"
export const UPDATE_USER_APPLICATIONS_FAILURE="UPDATE_USER_APPLICATIONS_FAILURE"

