export const FEED_DEVICE="FEED_DEVICE"
export const FEED_DEVICE_SUCCESS="FEED_DEVICE_SUCCESS"
export const FEED_DEVICE_FAILURE="FEED_DEVICE_FAILURE"


export const FEED_LOCAL_DEVICE="FEED_LOCAL_DEVICE"
export const FEED_LOCAL_DEVICE_SUCCESS="FEED_LOCAL_DEVICE_SUCCESS"
export const FEED_LOCAL_DEVICE_FAILURE="FEED_LOCAL_DEVICE_FAILURE"


export const UPDATE_DEVICE="UPDATE_DEVICE"
export const UPDATE_DEVICE_SUCCESS="UPDATE_DEVICE_SUCCESS"
export const UPDATE_DEVICE_FAILURE="UPDATE_DEVICE_FAILURE"


export const UPDATE_DEVICE_SIZE="UPDATE_DEVICE_SIZE"
export const UPDATE_DEVICE_SIZE_SUCCESS="UPDATE_DEVICE_SIZE_SUCCESS"
export const UPDATE_DEVICE_SIZE_FAILURE="UPDATE_DEVICE_SIZE_FAILURE"