

export const Hinglish = [
  { label: 'अ', text: ["a"] },
  { label: 'आ', text: ["aa", "A"] },
  { label: 'इ', text: ["i"] },
  { label: 'ई', text: ["ii", "I"] },
  { label: 'उ', text: ["u"] },
  { label: 'ऊ', text: ["uu", "U"] },
  { label: 'ऋ', text: ["R"] },
  { label: 'ॠ', text: ["RR"] },
  { label: 'लृ', text: ["lR"] },
  { label: 'ॡ', text: ["lRR"] },
  { label: 'ए', text: ["e"] },
  { label: 'ऐ', text: ["ai"] },
  { label: 'ओ', text: ["o"] },
  { label: 'औ', text: ["au"] },
  { label: 'अं', text: ["aM"] },
  { label: 'अः', text: ["aH"] },
  { label: 'क', text: ["ka"] },
  { label: 'ख', text: ["kha"] },
  { label: 'ग', text: ["ga"] },
  { label: 'घ', text: ["gha"] },
  { label: 'ङ', text: ["Ga"] },
  { label: 'च', text: ["ca"] },
  { label: 'छ', text: ["cha"] },
  { label: 'ज', text: ["ja"] },
  { label: 'झ', text: ["jha"] },
  { label: 'ञ', text: ["Ja"] },
  { label: 'ट', text: ["Ta"] },
  { label: 'ठ', text: ["Tha"] },
  { label: 'ड', text: ["Da"] },
  { label: 'ढ', text: ["Dha"] },
  { label: 'ण', text: ["Na"] },
  { label: 'त', text: ["ta"] },
  { label: 'थ', text: ["tha"] },
  { label: 'द', text: ["da"] },
  { label: 'ध', text: ["dha"] },
  { label: 'न', text: ["na"] },
  { label: 'प', text: ["pa"] },
  { label: 'फ', text: ["pha"] },
  { label: 'ब', text: ["ba"] },
  { label: 'भ', text: ["bha"] },
  { label: 'म', text: ["ma"] },
  { label: 'य', text: ["ya"] },
  { label: 'र', text: ["ra"] },
  { label: 'ल', text: ["la"] },
  { label: 'व', text: ["va"] },
  { label: 'क्ष', text: ["kSc"] },
  { label: 'श', text: ["za", "sha"] },
  { label: 'ष', text: ["Sa", "shha"] },
  { label: 'स', text: ["sa"] },
  { label: 'ह', text: ["ha"] },
  { label: 'ऽ', text: ["'a"] },
  { label: 'ज्ञ', text: ["jJ"] },
];
