export const GET_WALLET="GET_WALLET"
export const GET_WALLET_SUCCESS="GET_WALLET_SUCCESS"
export const GET_WALLET_FAILURE="GET_WALLET_FAILURE"


export const FIRST_INIT_WALLET="FIRST_INIT_WALLET"
export const FIRST_INIT_WALLET_SUCCESS="FIRST_INIT_WALLET_SUCCESS"
export const FIRST_INIT_WALLET_FAILURE="FIRST_INIT_WALLET_FAILURE"


export const REFILL_WALLET="REFIL_WALLET"
export const REFILL_WALLET_SUCCESS="REFIL_WALLET_SUCCESS"
export const REFILL_WALLET_FAILURE="REFIL_WALLET_FAILURE"


export const CONSUME_TO_ACTION="CONSUME_TO_ACTION"
export const CONSUME_TO_ACTION_SUCCESS="CONSUME_TO_ACTION_SUCCESS"
export const CONSUME_TO_ACTION_FAILURE="CONSUME_TO_ACTION_FAILURE"

export const RESET_WALLET="RESET_WALLET"

// action in action // varify action // perform sub action